[project]
name = "fluent-python"
version = "0.1.0"
description = ""
authors = [
    {name = "someXXYY",email = "betaXXX@gmail.com"}
]
requires-python = ">=3.7"
dependencies = [
]
packages = [
    { include = "18-asyncio" },
    { include = "18-asyncio-py3.7" },
    { include = "17-futures" },
    { include = "14-it-generator" }
]
[project.scripts]
spinner-thread = "18-asyncio.spinner_thread:main"
spinner-curio = "18-asyncio.spinner_curio:main"
spinner-await = "18-asyncio.spinner_await:main"
spinner-asyncio = "18-asyncio.spinner_asyncio:main"
tcp-charfinder = "18-asyncio.charfinder.tcp_charfinder:main"
http-charfinder = "18-asyncio.charfinder.http_charfinder:main"
charfinder = "18-asyncio.charfinder.charfinder:main"
spinner-thread-py37 = "18-asyncio-py3.7.spinner_thread:main"
spinner-asyncio-py37 = "18-asyncio-py3.7.spinner_asyncio:main"
countdown = "18-asyncio-py3.7.countdown:main"
tcp-charfinder-py37 = "18-asyncio-py3.7.charfinder.tcp_charfinder:main"
charfinder-py37 = "18-asyncio-py3.7.charfinder.charfinder:main"
arcfour-test = "17-futures.crypto.arcfour_test:main"
subfield = "14-it-generator.isis2json.subfield:main"
iso2709 = "14-it-generator.isis2json.iso2709:main"
isis2json = "14-it-generator.isis2json.isis2json:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
