# This workflow will install Python dependencies, build with Poetry, and run lint
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies with Poetry
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Chapter 1 data model examples
      working-directory: 01-data-model
      run: |
        poetry run python frenchdeck.py
        poetry run python vector2d.py
        poetry run python -m doctest frenchdeck.doctest
    - name: Run remaining chapter examples
      run: |
        poetry run python 02-array-seq/bisect_demo.py
        poetry run python 03-dict-set/strkeydict.py
        poetry run python 04-text-byte/numerics_demo.py
        poetry run python 05-1class-func/tagger.py
        poetry run python 06-dp-1class-func/strategy.py
        poetry run python 07-closure-deco/registration.py
        poetry run python 08-obj-ref/twilight_bus.py
        poetry run python 09-pythonic-obj/vector2d_v3.py
        poetry run python 10-seq-hacking/vector_v5.py
        poetry run python 11-iface-abc/bingo.py
        poetry run python 12-inheritance/diamond.py
        poetry run python 13-op-overloading/vector_v8.py
        pushd 14-it-generator
        poetry run python sentence_runner.py
        popd
        poetry run python 15-context-mngr/mirror.py
        poetry run python 16-coroutine/coroaverager3.py
        poetry run python 17-futures/crypto/arcfour_test.py
        poetry run python 17-futures-py3.7/demo_executor_map.py
        poetry run python 18-asyncio/spinner_thread.py
        poetry run python 18-asyncio/spinner_asyncio.py
        poetry run python 18-asyncio-py3.7/spinner_thread.py
        poetry run python 19-dyn-attr-prop/blackknight.py
        poetry run python 20-descriptor/descriptorkinds_dump.py
        poetry run python 21-class-metaprog/evaltime.py
